name: teste123
favicon: null
layout_spectrum: 0.23530777008272707
typography_spectrum: 0.6090205633081496
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
  brandStrength: 0.49320556968450546
  lightness: 0.46582119492813945
  saturation: 0.8759209215641022
  rhythmicContrast: 0.8851036340929568
purpose: []
